# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version:
        - 15.x
        - 14.x # Changing this? Remind to keep linter conditions below and in publish.yml aligned.
        - 12.x
        - 10.x
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run dev-up
    - run: npm run build
      # Only run linter once, for faster CI. Align the verisons of Node here with above and publish.yml.
    - if: matrix.platform == 'ubuntu-latest' && matrix.node-version == '14.x'
      run: npm run lint
    - run: npm test
